---
- name: Install postgres-xl_9.5
  hosts: target_hosts
  remote_user: postgres
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin"
  tasks:
    - name: Create directory "DATA/nodes"
      file:
        path: /home/postgres/DATA/pgxl/nodes
        state: directory

    - name: Create directory "postgres-xl"
      file:
        path: /home/postgres/postgres-xl
        state: directory

    - name: Run apt-get update
      become: true
      remote_user: postgres
      become_method: sudo
      apt:
        update_cache: yes

    - name: Install required packages
      become: true
      remote_user: postgres
      become_method: sudo
      apt:
        name:
          - build-essential
          - tar
          - libreadline-dev
          - zlib1g-dev
          - libssl-dev
          - libxml2-dev
          - flex
          - bison
        state: present

    - name: Clone repo
      git:
        repo: "git://git.postgresql.org/git/postgres-xl.git"
        dest: /home/postgres/postgres-xl

    - name: Configure
      shell: ./configure
      args:
        chdir: /home/postgres/postgres-xl

    #Opcjonalnie jesli wystapi problem podczas kompilacji z tym plikiem i funkcją "copy_file_range", której nazwe trzeba było zmienić.
    # - name: Copy file to remote host
    #   copy:
    #     src: copy_fetch.c
    #     dest: /home/postgres/postgres-xl/src/bin/pg_rewind/copy_fetch.c

    - name: Run 'make' command
      shell: make
      args:
        chdir: /home/postgres/postgres-xl

    - name: Run 'sudo make install' command
      shell: make install
      become: true
      remote_user: postgres
      become_method: sudo
      become_exe: /usr/bin/sudo
      args:
        chdir: /home/postgres/postgres-xl

    - name: Run 'make' command
      shell: make
      args:
        chdir: /home/postgres/postgres-xl/contrib

    - name: Run 'sudo make install' command
      shell: make install
      become: true
      remote_user: postgres
      become_method: sudo
      become_exe: /usr/bin/sudo
      args:
        chdir: /home/postgres/postgres-xl/contrib
