---
- name: Install required packages and copy postgres package to remote hosts and install postgres-xl
  hosts: target_hosts
  remote_user: postgres
  tasks:
    # - name: Run 'unninstall'
    #   shell: make uninstall
    #   become: true
    #   remote_user: vagrant
    #   become_method: sudo
    #   become_exe: /usr/bin/sudo
    #   args:
    #     chdir: /home/postgres/postgres-xl

    - name: Usun katalog "DATA/nodes"
      file:
        path: /home/postgres/DATA/pgxl/nodes
        state: absent

    - name: Utwórz katalog "DATA/nodes"
      file:
        path: /home/postgres/DATA/pgxl/nodes
        state: directory

    # - name: Utwórz katalog "$HOME/pgxc_ctl"
    #   file:
    #     path: /home/postgres/pgxc_ctl
    #     state: directory

    # - name: Usuń plik "postgres-xl"
    #   file:
    #     path: /home/postgres/postgres-xl/
    #     state: absent

    # - name: Usuń plik "postgres-xl.gz"
    #   file:
    #     path: /home/postgres/postgres-xl.gz
    #     state: absent

    # - name: Utwórz katalog "postgres-xl"
    #   file:
    #     path: /home/postgres/postgres-xl
    #     state: directory

    # - name: Wykonaj apt-get update
    #   become: true
    #   remote_user: postgres
    #   become_method: sudo
    #   apt:
    #     update_cache: yes

    # - name: Install required packages
    #   become: true
    #   remote_user: postgres
    #   become_method: sudo
    #   apt:
    #     name:
    #       - build-essential
    #       - tar
    #       - libreadline-dev
    #       - zlib1g-dev
    #       - libssl-dev
    #       - libxml2-dev
    #       - flex
    #     state: present

    # - name: Copy file to remote host
    #   copy:
    #     src: postgres-xl-10r1.1.tar.gz
    #     dest: /home/postgres/

    # - name: Extract file
    #   unarchive:
    #     src: /home/postgres/postgres-xl-10r1.1.tar.gz
    #     dest: /home/postgres/postgres-xl
    #     remote_src: yes
    #     extra_opts: "--strip-components=1"

    # - name: Run './configure' command
    #   shell: ./configure
    #   args:
    #     chdir: /home/postgres/postgres-xl

    # - name: Run 'make' command
    #   shell: make
    #   args:
    #     chdir: /home/postgres/postgres-xl

    # - name: Run 'sudo make install' command
    #   shell: make install
    #   become: true
    #   remote_user: postgres
    #   become_method: sudo
    #   args:
    #     chdir: /home/postgres/postgres-xl

    # - name: Copy file to remote host
    #   copy:
    #     src: postgres-xl-9.5r1.6.tar.bz2
    #     dest: /home/postgres/

    # - name: Extract file
    #   unarchive:
    #     src: /home/postgres/postgres-xl-9.5r1.6.tar.bz2
    #     dest: /home/postgres/postgres-xl
    #     remote_src: yes
    #     extra_opts: "--strip-components=1"

    # - name: Run './configure' command
    #   shell: ./configure
    #   args:
    #     chdir: /home/postgres/postgres-xl

    # - name: Run 'make' command
    #   shell: make
    #   args:
    #     chdir: /home/postgres/postgres-xl

    # - name: Run 'sudo make install' command
    #   shell: make install
    #   become: true
    #   remote_user: postgres
    #   become_method: sudo
    #   args:
    #     chdir: /home/postgres/postgres-xl
