---
- name: Update .profile
  hosts: target_hosts
  remote_user: postgres
  tasks:
    - name: Dodaj linijkę do .profile
      lineinfile:
        path: ~/.profile
        line: 'export LD_LIBRARY_PATH="/usr/local/pgsql/lib"'
        insertafter: EOF
